### ISSUE TITLE
Can you please pass my request for data?

### ISSUE THREAD

**Issue by jch12138** [YueAWu/MCer#2]
I really need these now.thks

**Comment by YueAWu** [comment]
Download permission has been modified, you can download the data now. Sorry for my oversight.

Best，
Juwei Yue


| |
岳聚微
|
|
***@***.***
|
On 3/1/2022 ***@***.***> wrote：

I really need these now.thks

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jch12138** [comment]
thank you~
